# Generated by Django 4.2.4 on 2023-09-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv_data',
            old_name='total_emaployee_estimate',
            new_name='total_employee_estimate',
        ),
    ]
