# Generated by Django 4.2.4 on 2023-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count_app', '0004_alter_csv_data_total_employee_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_data',
            name='total_employee_estimate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
